apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-server
  template:
    metadata:
      labels:
        app: ai-server
    spec:
      imagePullSecrets:
        - name: ncr-secret
      containers:
        - name: ai-server
          image: contest-cluster54-registry.kr.ncr.ntruss.com/ai-server:latest
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: LLM_BASE_URL
              value: "http://ollama-service:11434"
            - name: EMBED_ENDPOINT
              value: "http://ollama-service:11434"
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: DEBUG_LLM
              value: "true"
            - name: DEBUG_CTRL
              value: "true"
---
apiVersion: v1
kind: Service
metadata:
  name: ai-server-service
spec:
  selector:
    app: ai-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
