apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-server
spec:
  replicas: 4
  selector:
    matchLabels:
      app: ai-server
  template:
    metadata:
      labels:
        app: ai-server
    spec:
      containers:
        - name: ai-server
          image: contest-cluster54-registry.kr.ncr.ntruss.com/ai-server:latest
          ports:
            - containerPort: 8000
          env:
            - name: PYTHONUNBUFFERED
              value: "1"
---
apiVersion: v1
kind: Service
metadata:
  name: ai-server-service
spec:
  selector:
    app: ai-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer
