apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-server
  template:
    metadata:
      labels:
        app: ai-server
    spec:
      imagePullSecrets:
        - name: ncr-secret
      containers:
        - name: ai-server
          image: contest-cluster54-registry.kr.ncr.ntruss.com/ai-server:latest
          ports:
            - containerPort: 8000
          env:
            # --- 기본 설정 ---
            - name: PYTHONUNBUFFERED
              value: "1"
            - name: LOG_LEVEL
              value: "DEBUG"
            - name: DEBUG_LLM
              value: "true"
            - name: DEBUG_CTRL
              value: "true"

            # --- PostgreSQL 연결 정보 ---
            - name: PG_HOST
              value: "postgres-service"   # ✅ 실제 postgres 서비스명으로 변경 필요
            - name: PG_PORT
              value: "5432"
            - name: PG_DATABASE
              value: "FilterFacts"
            - name: PG_USER
              value: "postgres"
            - name: PG_PASSWORD
              value: "3684"               # ✅ 실제 비밀번호 입력

            # --- Ollama (LLM) 연결 정보 ---
            - name: LLM_BASE_URL
              value: "http://ollama-service:11434"
            - name: EMBED_ENDPOINT
              value: "http://ollama-service:11434"

---
apiVersion: v1
kind: Service
metadata:
  name: ai-server-service
spec:
  selector:
    app: ai-server
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: ClusterIP
