# nonk8s
apiVersion: apps/v1
kind: Deployment
metadata:
  name: f-f-backend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: f-f-backend
  template:
    metadata:
      labels:
        app: f-f-backend
    spec:
      containers:
        - name: f-f-backend
          image: hf9fzsj9.kr.private-ncr.ntruss.com/filterfacts-backend:__TAG__
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
          env:
            # ✅ PostgreSQL 설정
            - name: SPRING_DATASOURCE_URL
              value: "jdbc:postgresql://postgres-service:5432/FilterFacts"
            - name: SPRING_DATASOURCE_USERNAME
              value: "postgres"
            - name: SPRING_DATASOURCE_PASSWORD
              value: "3684"

            # ✅ JPA 설정
            - name: SPRING_PROFILES_ACTIVE
              value: "prod"

            # ✅ Redis 설정 (새로 추가된 부분)
            - name: REDIS_HOST
              value: "redis-service"
            - name: REDIS_PORT
              value: "6379"
      imagePullSecrets:
        - name: ncr-secret
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: f-f-backend
  ports:
    - port: 80
      targetPort: 8080
