apiVersion: apps/v1
kind: Deployment
metadata:
  name: f-f-backend

spec:
  replicas: 1
  selector:
    matchLabels:
      app: f-f-backend
  template:
    metadata:
      labels:
        app: f-f-backend
    spec:
      containers:
        - name: f-f-backend
          image: contest-cluster54-registry.kr.ncr.ntruss.com/filterfacts-backend:latest
          ports:
            - containerPort: 8080
          imagePullPolicy: Always
      imagePullSecrets:          # ✅ 여기가 추가 포인트
        - name: ncr-secret       # 위에서 만든 secret 이름과 동일해야 함
---
apiVersion: v1
kind: Service
metadata:
  name: backend-service
spec:
  type: LoadBalancer
  selector:
    app: f-f-backend
  ports:
    - port: 80
      targetPort: 8080
