# =============================
# Persistent Volume Claim (PVC)
# =============================
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ollama-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi  # ✅ 모델 캐시 용량 (필요시 조정)
  storageClassName: nks-block-storage  # ✅ Naver Cloud 기본 스토리지 클래스명

---
# =============================
# Ollama Deployment (무중단)
# =============================
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ollama
spec:
  replicas: 1
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 0  # 기존 Pod 중단 없이
      maxSurge: 1        # 새 Pod를 먼저 띄운 후 교체
  selector:
    matchLabels:
      app: ollama
  template:
    metadata:
      labels:
        app: ollama
    spec:
      containers:
        - name: ollama
          image: ollama/ollama:latest
          ports:
            - containerPort: 11434

          resources:
            requests:
              cpu: "1000m"
              memory: "1.5Gi"
            limits:
              cpu: "2"
              memory: "4Gi"

          volumeMounts:
            - name: ollama-data
              mountPath: /root/.ollama

      volumes:
        - name: ollama-data
          persistentVolumeClaim:
            claimName: ollama-pvc  # ✅ PVC 연결

---
# =============================
# Ollama Service (외부 접근)
# =============================
apiVersion: v1
kind: Service
metadata:
  name: ollama-service
spec:
  selector:
    app: ollama
  ports:
    - protocol: TCP
      port: 11434
      targetPort: 11434
  type: LoadBalancer
